CREATE TABLE [dbo].[cfm_impairments] (
    [cfm_impairment_id]  INT          IDENTITY (1, 1) NOT NULL,
    [cfm_file_id]        INT          NOT NULL,
    [alzheimers]         VARCHAR (50) NULL,
    [arthritis]          VARCHAR (50) NULL,
    [prostate]           VARCHAR (50) NULL,
    [cancer]             VARCHAR (50) NULL,
    [diabetes]           VARCHAR (50) NULL,
    [gastroIntestinal]   VARCHAR (50) NULL,
    [hearing_impairment] VARCHAR (50) NULL,
    [heart]              VARCHAR (50) NULL,
    [kidney]             VARCHAR (50) NULL,
    [respiratory]        VARCHAR (50) NULL,
    [speech_impairment]  VARCHAR (50) NULL,
    [stroke]             VARCHAR (50) NULL,
    [eye_disease]        VARCHAR (50) NULL,
    [neurological]       VARCHAR (50) NULL,
    [infectious]         VARCHAR (50) NULL,
    [health_pain]        VARCHAR (50) NULL,
    [health_other]       VARCHAR (50) NULL,
    [health_other2]      VARCHAR (50) NULL,
    [allergy]            VARCHAR (50) NULL,
    [dental]             VARCHAR (50) NULL,
    [liver]              VARCHAR (50) NULL,
    [sleep_disorder]     VARCHAR (50) NULL,
    [tenant_id]          INT          NULL,
    CONSTRAINT [PK_cfm_impairments] PRIMARY KEY CLUSTERED ([cfm_impairment_id] ASC) WITH (FILLFACTOR = 90)
);

