CREATE TABLE [dbo].[client_questionaire_service] (
    [questionaire_service_id]   INT              IDENTITY (1, 1) NOT NULL,
    [questionaire_service_guid] UNIQUEIDENTIFIER NULL,
    [questionaire_id]           INT              NULL,
    [type_id]                   INT              NULL,
    [ads_ccp]                   VARCHAR (50)     NULL,
    [ads_transport]             VARCHAR (50)     NULL,
    [ads]                       VARCHAR (50)     NULL,
    [adult_protective]          VARCHAR (10)     NULL,
    [advance_directives]        VARCHAR (10)     NULL,
    [advocacy_groups]           VARCHAR (10)     NULL,
    [ccp_homemaker]             VARCHAR (10)     NULL,
    [chore_housekeeping]        VARCHAR (10)     NULL,
    [counseling]                VARCHAR (10)     NULL,
    [ers_ccp]                   VARCHAR (10)     NULL,
    [ers]                       VARCHAR (10)     NULL,
    [entitlements]              VARCHAR (10)     NULL,
    [friendly_visiting]         VARCHAR (10)     NULL,
    [grg_program]               VARCHAR (10)     NULL,
    [home_deliver_meals]        VARCHAR (10)     NULL,
    [home_health_care]          VARCHAR (10)     NULL,
    [housing]                   VARCHAR (10)     NULL,
    [legal]                     VARCHAR (10)     NULL,
    [money_management]          VARCHAR (10)     NULL,
    [private_home_care]         VARCHAR (10)     NULL,
    [private_care_mgmt]         VARCHAR (10)     NULL,
    [respite]                   VARCHAR (10)     NULL,
    [retirement]                VARCHAR (10)     NULL,
    [support_groups]            VARCHAR (10)     NULL,
    [transportation]            VARCHAR (10)     NULL,
    [tenant_id]                 INT              NULL,
    CONSTRAINT [PK_client_questionaire_service] PRIMARY KEY CLUSTERED ([questionaire_service_id] ASC)
);

