CREATE TABLE [dbo].[comm_educ_event] (
    [COMM_EDUC_EVENT_ID]             INT            IDENTITY (1, 1) NOT NULL,
    [ORGANIZATION_ID]                INT            NOT NULL,
    [EVENT_DATE]                     DATETIME       NOT NULL,
    [ATTENDEES]                      INT            NULL,
    [MALES]                          INT            NULL,
    [FEMALES]                        INT            NULL,
    [BLACKS]                         INT            NULL,
    [ASIANS]                         INT            NULL,
    [INDIANS]                        INT            NULL,
    [HISPANICS]                      INT            NULL,
    [WHITES]                         INT            NULL,
    [LOW_INCOME]                     INT            NULL,
    [LIVING_ALONE]                   INT            NULL,
    [OVER74]                         INT            NULL,
    [FRAIL_DISABLED]                 INT            NULL,
    [LIMITED_ENGLISH]                INT            NULL,
    [MEMO]                           VARCHAR (1000) NULL,
    [FEE]                            MONEY          NULL,
    [CONSTITUENT_ID]                 INT            NULL,
    [EVENT_TITLE]                    VARCHAR (100)  NULL,
    [LANGUAGE]                       INT            NULL,
    [ContactName]                    VARCHAR (50)   NULL,
    [ContactPhone]                   CHAR (10)      NULL,
    [ShipId]                         VARCHAR (50)   NULL,
    [TopicFraudAndAbuse]             BIT            NULL,
    [TopicMedicareAB]                BIT            NULL,
    [TopicMedigap]                   BIT            NULL,
    [TopicMedicareD]                 BIT            NULL,
    [TopicNonRenewal]                BIT            NULL,
    [TopicLowIncomeSubsidy]          BIT            NULL,
    [TopicStatePrograms]             BIT            NULL,
    [TopicLongTermCare]              BIT            NULL,
    [TopicOtherProgram]              BIT            NULL,
    [TopicOtherProgramDescription]   VARCHAR (50)   NULL,
    [TargetMedicareOver65]           BIT            NULL,
    [TargetMedicareUnder65]          BIT            NULL,
    [TargetFamilyCaregivers]         BIT            NULL,
    [TargetNursingHomePersonnel]     BIT            NULL,
    [TargetSeniorCenterPersonnel]    BIT            NULL,
    [TargetHospitalMedicalPersonnel] BIT            NULL,
    [TargetHousingPersonnel]         BIT            NULL,
    [TargetOtherAgingPersonnel]      BIT            NULL,
    [TargetWhite]                    BIT            NULL,
    [TargetAsian]                    BIT            NULL,
    [TargetAmericanIndian]           BIT            NULL,
    [TargetBlack]                    BIT            NULL,
    [TargetHispanic]                 BIT            NULL,
    [TargetLowIncome]                BIT            NULL,
    [TargetRural]                    BIT            NULL,
    [TargetOtherMinority]            BIT            NULL,
    [TargetOtherMinorityDescription] VARCHAR (50)   NULL,
    [IsPresentation]                 BIT            NULL,
    [IsBooth]                        BIT            NULL,
    [IsNewsprint]                    BIT            NULL,
    [IsTVShow]                       BIT            NULL,
    [IsRadioShow]                    BIT            NULL,
    [IsWebsiteEvent]                 BIT            NULL,
    [IsEnrollmentEvent]              BIT            NULL,
    [IsTrainingforExisting]          BIT            NULL,
    [IsTrainingforNew]               BIT            NULL,
    [IsOther]                        BIT            NULL,
    [IsOtherDescription]             VARCHAR (50)   NULL,
    [StartTime]                      VARCHAR (10)   NULL,
    [EndTime]                        VARCHAR (10)   NULL,
    [InsertDt]                       DATETIME       NULL,
    [UpdateDt]                       DATETIME       NULL,
    [InsertUserId]                   CHAR (10)      NULL,
    [UpdateUserId]                   CHAR (10)      NULL,
    [tenant_id]                      INT            NULL,
    CONSTRAINT [PK__COMM_EDUC_EVENT__14E61A24] PRIMARY KEY NONCLUSTERED ([COMM_EDUC_EVENT_ID] ASC) WITH (FILLFACTOR = 90)
);

