CREATE TABLE [dbo].[constituent] (
    [CONSTITUENT_ID]          INT           NOT NULL,
    [TITLE_ID]                INT           NULL,
    [FIRST_NAME]              NVARCHAR (50) NULL,
    [MIDDLE_NAME]             NVARCHAR (50) NULL,
    [LAST_NAME]               NVARCHAR (50) NULL,
    [SUFFIX_ID]               SMALLINT      NULL,
    [NICKNAME]                NVARCHAR (50) NULL,
    [maiden_name]             NVARCHAR (50) NULL,
    [ADDR1]                   NVARCHAR (80) NULL,
    [ADDR2]                   NVARCHAR (80) NULL,
    [CITY]                    NVARCHAR (50) NULL,
    [CITY_ID]                 INT           NULL,
    [TOWNSHIP_ID]             INT           NULL,
    [STATE_ID]                INT           NULL,
    [state_cd]                CHAR (2)      NULL,
    [ZIP_ID]                  INT           NULL,
    [ZIP_CODE]                NVARCHAR (50) NULL,
    [FEDERAL_ID]              NVARCHAR (50) NULL,
    [BIRTH_DATE]              DATETIME2 (7) NULL,
    [GENDER]                  INT           NULL,
    [MINORITY_ID]             INT           NULL,
    [income_level_id]         INT           NULL,
    [LIVING_ALONE]            BIT           NULL,
    [FRAIL_DISABLED]          BIT           NULL,
    [LIMITED_ENGLISH]         BIT           NULL,
    [lives_in_nursing_home]   BIT           NULL,
    [ethnicity_id]            INT           NULL,
    [case_worker_risk]        BIT           NULL,
    [female_headed_household] BIT           NULL,
    [homeless]                BIT           NULL,
    [created_by]              NVARCHAR (50) NULL,
    [created_date]            DATETIME2 (7) NULL,
    [updated_by]              NVARCHAR (50) NULL,
    [updated_date]            DATETIME2 (7) NULL,
    CONSTRAINT [PK__CONSTI_04032001155313001] PRIMARY KEY NONCLUSTERED ([CONSTITUENT_ID] ASC) WITH (FILLFACTOR = 90)
);

