CREATE TABLE [dbo].[constituent_tracking] (
    [constituent_tracking_id]     INT          IDENTITY (1, 1) NOT NULL,
    [constituent_id]              INT          NOT NULL,
    [adult_day_id]                INT          NULL,
    [homemaker_id]                INT          NULL,
    [homemaker_preferred]         CHAR (1)     NULL,
    [titleIII_meals_id]           INT          NULL,
    [non_titleIII_meals_id]       INT          NULL,
    [case_management_program_id]  INT          NULL,
    [case_management_waiting]     CHAR (1)     NULL,
    [grandparents]                CHAR (1)     NULL,
    [money_management_id]         INT          NULL,
    [friendly_visiting_id]        INT          NULL,
    [translation_need_id]         INT          NULL,
    [housing_id]                  INT          NULL,
    [preferred_language_id]       INT          NULL,
    [abuse_id]                    INT          NULL,
    [support_group_id]            INT          NULL,
    [face_to_face_date]           DATETIME     NULL,
    [goal_setting_date]           DATETIME     NULL,
    [circuit_breaker_date]        DATETIME     NULL,
    [respite_date]                DATETIME     NULL,
    [guardianship_person]         INT          NULL,
    [guardianship_estate]         INT          NULL,
    [guardianship_type]           INT          NULL,
    [guardian_name]               VARCHAR (50) NULL,
    [guardian_phone]              CHAR (10)    NULL,
    [self_neglect]                CHAR (1)     NULL,
    [vulnerable_client]           CHAR (1)     NULL,
    [case_worker_risk]            CHAR (1)     NULL,
    [homeless]                    CHAR (1)     NULL,
    [female_headed_household]     CHAR (1)     NULL,
    [pet]                         CHAR (1)     NULL,
    [corporate_des_plaines]       CHAR (1)     NULL,
    [grandchildren_count]         INT          NULL,
    [contract_code]               VARCHAR (3)  NULL,
    [medicare]                    CHAR (1)     NULL,
    [medicaid]                    CHAR (1)     NULL,
    [medicaid_type_id]            INT          NULL,
    [eccpis_id]                   VARCHAR (50) NULL,
    [rin_number]                  VARCHAR (20) NULL,
    [plan_of_care_constituent_id] INT          NULL,
    [preferred_worker_name]       VARCHAR (50) NULL,
    [gender_description]          VARCHAR (50) NULL,
    [tenant_id]                   INT          NULL,
    CONSTRAINT [PK_constituent_svss] PRIMARY KEY CLUSTERED ([constituent_tracking_id] ASC) WITH (FILLFACTOR = 90)
);

