CREATE TABLE [dbo].[constituent_audit] (
    [CONSTITUENT_AUDIT_ID]    INT           IDENTITY (1, 1) NOT NULL,
    [CONSTITUENT_ID]          INT           NOT NULL,
    [TITLE_ID]                INT           NULL,
    [TITLE]                   VARCHAR (50)  NULL,
    [FIRST_NAME]              VARCHAR (50)  NULL,
    [MIDDLE_NAME]             VARCHAR (50)  NULL,
    [LAST_NAME]               VARCHAR (50)  NULL,
    [SUFFIX_ID]               SMALLINT      NULL,
    [SUFFIX]                  VARCHAR (50)  NULL,
    [NICKNAME]                VARCHAR (50)  NULL,
    [ADDR1]                   VARCHAR (80)  NULL,
    [ADDR2]                   VARCHAR (80)  NULL,
    [CITY]                    VARCHAR (50)  NULL,
    [CITY_ID]                 INT           NULL,
    [TOWNSHIP_ID]             INT           NULL,
    [TOWNSHIP]                VARCHAR (50)  NULL,
    [STATE_ID]                INT           NULL,
    [STATE_NAME]              VARCHAR (50)  NULL,
    [ZIP_ID]                  INT           NULL,
    [ZIP_NAME]                VARCHAR (50)  NULL,
    [FEDERAL_ID]              VARCHAR (11)  NULL,
    [BIRTH_DATE]              DATETIME      NULL,
    [GENDER]                  INT           NULL,
    [GENDER_NAME]             VARCHAR (50)  NULL,
    [MINORITY_ID]             INT           NULL,
    [MINORITY_NAME]           VARCHAR (50)  NULL,
    [POVERTY]                 CHAR (1)      NULL,
    [VERY_LOW_INCOME]         CHAR (1)      NULL,
    [LIVING_ALONE]            CHAR (1)      NULL,
    [FRAIL_DISABLED]          CHAR (1)      NULL,
    [LIMITED_ENGLISH]         CHAR (1)      NULL,
    [STATUS_ID]               INT           NULL,
    [END_DATE]                DATETIME      NULL,
    [ZIP_CODE]                VARCHAR (10)  NULL,
    [EXTRACT_STATUS]          INT           NULL,
    [ALLOW_EXTRACT]           INT           NULL,
    [EXTRACT_DATE]            DATETIME      NULL,
    [caregiver]               CHAR (1)      NULL,
    [caregiver_relationship]  INT           NULL,
    [caregiver_id]            INT           NULL,
    [caregiver_name]          VARCHAR (100) NULL,
    [second_contact_date]     DATETIME      NULL,
    [how_discharge_date]      DATETIME      NULL,
    [reason_for_discharge]    INT           NULL,
    [lives_in_nursing_home]   CHAR (1)      NULL,
    [maiden_name]             VARCHAR (30)  NULL,
    [import_id]               VARCHAR (50)  NULL,
    [low_income]              CHAR (1)      NULL,
    [moderate_income]         CHAR (1)      NULL,
    [higher_income]           CHAR (1)      NULL,
    [income_level_id]         CHAR (1)      NULL,
    [income_level]            VARCHAR (50)  NULL,
    [extract_address_changed] CHAR (1)      NULL,
    [ethnicity_id]            INT           NULL,
    [ethnicity_name]          VARCHAR (50)  NULL,
    [updated_by]              CHAR (10)     NULL,
    [created_by]              CHAR (10)     NULL,
    [updated_date]            DATETIME      NULL,
    [created_date]            DATETIME      NULL,
    [case_worker_risk]        CHAR (1)      NULL,
    [homeless]                CHAR (1)      NULL,
    [female_headed_household] CHAR (1)      NULL,
    [pet]                     CHAR (1)      NULL,
    [preferred_language_id]   INT           NULL,
    [preferred_language]      VARCHAR (50)  NULL,
    [AUDIT_DATE]              DATETIME      NULL,
    [AUDIT_BY]                CHAR (10)     NULL,
    [AUDIT_TYPE]              CHAR (1)      NULL,
    [tenant_id]               INT           NULL,
    CONSTRAINT [PK_CONSTITUENT_AUDIT] PRIMARY KEY CLUSTERED ([CONSTITUENT_AUDIT_ID] ASC) WITH (FILLFACTOR = 90)
);

