CREATE TABLE [dbo].[CONSTITUENT_STATUS] (
    [UNQ_ID]                INT       IDENTITY (1, 1) NOT NULL,
    [CONSTITUENT_ID]        INT       NOT NULL,
    [CONSTITUENT_TYPE_CODE] CHAR (2)  NULL,
    [START_DATE]            DATETIME  NULL,
    [END_DATE]              DATETIME  NULL,
    [CONSTITUENT_TYPE_ID]   INT       NULL,
    [CREATED_BY]            CHAR (10) NULL,
    [CREATED_DATE]          DATETIME  NULL,
    [UPDATED_BY]            CHAR (10) NULL,
    [UPDATED_DATE]          DATETIME  NULL,
    [tenant_id]             INT       NULL,
    CONSTRAINT [PK__CONSTITUENT_STAT__681373AD] PRIMARY KEY NONCLUSTERED ([UNQ_ID] ASC) WITH (FILLFACTOR = 90)
);

