CREATE TABLE [dbo].[CONSTITUENT_PROVIDER] (
    [CONSTITUENT_PROVIDER_ID] INT IDENTITY (1, 1) NOT NULL,
    [CONSTITUENT_ID]          INT NOT NULL,
    [PROVIDER_ID]             INT NOT NULL,
    [tenant_id]               INT NULL,
    CONSTRAINT [PK__CONSTITUENT_PROV__756D6ECB] PRIMARY KEY NONCLUSTERED ([CONSTITUENT_PROVIDER_ID] ASC) WITH (FILLFACTOR = 90)
);

