CREATE TABLE [dbo].[CONSTITUENT_TYPE] (
    [CONSTITUENT_TYPE_ID]          INT          IDENTITY (1, 1) NOT NULL,
    [CONSTITUENT_TYPE_CODE]        CHAR (2)     NOT NULL,
    [CONSTITUENT_TYPE_DESCRIPTION] VARCHAR (50) NOT NULL,
    [tenant_id]                    INT          NULL,
    CONSTRAINT [PK__CONSTITUENT_TYPE__3DE82FB7] PRIMARY KEY NONCLUSTERED ([CONSTITUENT_TYPE_CODE] ASC) WITH (FILLFACTOR = 90)
);

