CREATE TABLE [dbo].[MARITAL_STATUS] (
    [MARITAL_STATUS_ID]   INT          IDENTITY (1, 1) NOT NULL,
    [MARITAL_STATUS_CODE] CHAR (1)     NOT NULL,
    [MARITAL_TYPE]        VARCHAR (50) NOT NULL,
    [tenant_id]           INT          NULL,
    CONSTRAINT [PK__MARITAL_STATUS__3FD07829] PRIMARY KEY NONCLUSTERED ([MARITAL_STATUS_ID] ASC) WITH (FILLFACTOR = 90)
);

