CREATE TABLE [dbo].[napis_medicare] (
    [napis_medicare_id]        INT           IDENTITY (1, 1) NOT NULL,
    [napis_form_id]            INT           NOT NULL,
    [shipshap_date]            DATETIME      NULL,
    [location_zip]             CHAR (10)     NULL,
    [update_date]              DATETIME      NULL,
    [ship_id]                  VARCHAR (50)  NULL,
    [create_userid]            VARCHAR (10)  NULL,
    [create_date]              DATETIME      NULL,
    [update_userid]            VARCHAR (10)  NULL,
    [coupleInd]                BIT           NULL,
    [beneficiaryInd]           BIT           NULL,
    [caregiverInd]             BIT           NULL,
    [agencyInd]                BIT           NULL,
    [learnedCMSInd]            BIT           NULL,
    [learnedAgencyInd]         BIT           NULL,
    [learnedNotCollectedInd]   BIT           NULL,
    [learnedPresentationInd]   BIT           NULL,
    [learnedFriendInd]         BIT           NULL,
    [learnedStateSpecificInd]  BIT           NULL,
    [learnedOtherInd]          BIT           NULL,
    [initialQuickCallInd]      BIT           NULL,
    [initialTelephoneInd]      BIT           NULL,
    [intialEmailInd]           BIT           NULL,
    [initialInPersonSiteInd]   BIT           NULL,
    [initialInPersonHomeInd]   BIT           NULL,
    [multipleContactDate]      DATETIME      NULL,
    [multipleQuickCallInd]     BIT           NULL,
    [multipleTelephoneInd]     BIT           NULL,
    [multipleEmailInd]         BIT           NULL,
    [multipleInPersonSiteInd]  BIT           NULL,
    [multipleInPersonHomeInd]  BIT           NULL,
    [representativeName]       VARCHAR (100) NULL,
    [representativePhone]      CHAR (10)     NULL,
    [medicareFraudInd]         BIT           NULL,
    [pdpEligibilityInd]        BIT           NULL,
    [pdpEnrollmentInd]         BIT           NULL,
    [pdpAppealsInd]            BIT           NULL,
    [pdpLowIncomeInd]          BIT           NULL,
    [pdpClaimsInd]             BIT           NULL,
    [paStateAssistInd]         BIT           NULL,
    [paUnionEmployeeInd]       BIT           NULL,
    [paOtherInd]               BIT           NULL,
    [paUnionInd]               BIT           NULL,
    [paDiscountPlanInd]        BIT           NULL,
    [MedicareEnrollmentInd]    BIT           NULL,
    [MedicareClaimsInd]        BIT           NULL,
    [MedicareAppealsInd]       BIT           NULL,
    [HealthPlansEnrollmentInd] BIT           NULL,
    [HealthPlansPlanInd]       BIT           NULL,
    [HealthPlansAppearsInd]    BIT           NULL,
    [MedicaidQMBInd]           BIT           NULL,
    [MedicaidOther]            BIT           NULL,
    [MedigapEnrollmentInd]     BIT           NULL,
    [MedigapChangeInd]         BIT           NULL,
    [MedigapClaimsInd]         BIT           NULL,
    [OtherLTCInd]              BIT           NULL,
    [OtherMilitaryInd]         BIT           NULL,
    [OtherServiceIssuesInd]    BIT           NULL,
    [OtherFraudInd]            BIT           NULL,
    [OtherEmployerInd]         BIT           NULL,
    [OtherOtherInd]            BIT           NULL,
    [AssistanceDrugCardInd]    BIT           NULL,
    [AssistanceILCaresInd]     BIT           NULL,
    [AssistanceISaveRxInd]     BIT           NULL,
    [tenant_id]                INT           NULL,
    CONSTRAINT [PK_napis_shipshap] PRIMARY KEY CLUSTERED ([napis_medicare_id] ASC) WITH (FILLFACTOR = 90)
);

