CREATE TABLE [dbo].[napis_intake_ccp] (
    [napis_intake_ccp_id]        INT          IDENTITY (1, 1) NOT NULL,
    [napis_intake_id]            INT          NULL,
    [beam_date]                  DATETIME     NULL,
    [under_asset_limit]          BIT          NULL,
    [under_medicaid_limit]       BIT          NULL,
    [under_psi_limit]            BIT          NULL,
    [medicaid_recipient]         BIT          NULL,
    [medicaid_application_sent]  BIT          NULL,
    [medicare_recipient]         BIT          NULL,
    [mco_type_id]                INT          NULL,
    [rin_number]                 VARCHAR (50) NULL,
    [active_rin]                 BIT          NULL,
    [pss_date]                   DATE         NULL,
    [is_ssn_verification]        BIT          NULL,
    [is_active_mco]              BIT          NULL,
    [is_mco_end]                 BIT          NULL,
    [ssn_verification_date]      DATE         NULL,
    [mco_end_date]               DATE         NULL,
    [asset_level_id]             INT          NULL,
    [lived_in_us]                BIT          NULL,
    [lived_in_il]                BIT          NULL,
    [va_benefits]                BIT          NULL,
    [va_discussed]               BIT          NULL,
    [va_discussed_date]          DATE         NULL,
    [spouse_dob]                 DATE         NULL,
    [applicant_age]              INT          NULL,
    [spouse_age]                 INT          NULL,
    [apply_as_individual]        BIT          NULL,
    [spouse_medicaid_recipient]  BIT          NULL,
    [spouse_receiving_services]  BIT          NULL,
    [married_asset_level_id]     INT          NULL,
    [married_medicare_recipient] BIT          NULL,
    [married_lived_in_us]        BIT          NULL,
    [married_lived_in_il]        BIT          NULL,
    [married_va_benefits]        BIT          NULL,
    [spouse_lived_in_us]         BIT          NULL,
    [spouse_lived_in_il]         BIT          NULL,
    [spouse_va_benefits]         BIT          NULL,
    [tenant_id]                  INT          NULL,
    CONSTRAINT [PK_napis_intake_ccp] PRIMARY KEY CLUSTERED ([napis_intake_ccp_id] ASC)
);

