CREATE TABLE [dbo].[respite_event_gap_fill] (
    [respite_event_gap_fill_id]        INT           IDENTITY (1, 1) NOT NULL,
    [interview_date]                   DATETIME      NULL,
    [fiscal_year_id]                   INT           NULL,
    [agency]                           VARCHAR (50)  NULL,
    [status_id]                        INT           NULL,
    [denial_reason]                    VARCHAR (100) NULL,
    [constituent_id]                   INT           NULL,
    [case_manager_id]                  INT           NULL,
    [social_security_number]           CHAR (11)     NULL,
    [ers_system]                       FLOAT (53)    NULL,
    [home_equipment]                   FLOAT (53)    NULL,
    [home_renovation]                  FLOAT (53)    NULL,
    [temporary_housing]                FLOAT (53)    NULL,
    [housing_other]                    FLOAT (53)    NULL,
    [housing_other_description]        VARCHAR (100) NULL,
    [housing_utilities]                FLOAT (53)    NULL,
    [prescription_medication]          FLOAT (53)    NULL,
    [durable_medical_equipment]        FLOAT (53)    NULL,
    [consumable_medical_equipment]     FLOAT (53)    NULL,
    [medical_other]                    FLOAT (53)    NULL,
    [medical_other_description]        VARCHAR (100) NULL,
    [transportation_other]             FLOAT (53)    NULL,
    [transportation_other_description] VARCHAR (50)  NULL,
    [legal_other]                      FLOAT (53)    NULL,
    [legal_other_description]          VARCHAR (50)  NULL,
    [pharmacy]                         FLOAT (53)    NULL,
    [pharmacy_description]             VARCHAR (50)  NULL,
    [other]                            FLOAT (53)    NULL,
    [other_description]                VARCHAR (50)  NULL,
    [plans]                            VARCHAR (500) NULL,
    [approved_by]                      VARCHAR (20)  NULL,
    [approved_date]                    DATETIME      NULL,
    [created_by]                       VARCHAR (20)  NULL,
    [created_date]                     DATETIME      NULL,
    [paid_by]                          VARCHAR (20)  NULL,
    [paid_date]                        DATETIME      NULL,
    [amount]                           FLOAT (53)    NULL,
    [location_id]                      INT           NULL,
    [payee]                            VARCHAR (50)  NULL,
    [provider_id]                      INT           NULL,
    [gap_fill_type_id]                 INT           NULL,
    [client_under_55]                  BIT           NULL,
    [client_55_to_59]                  BIT           NULL,
    [client_over_60]                   BIT           NULL,
    [funds_approved]                   BIT           NULL,
    [funds_denied]                     BIT           NULL,
    [funds_approved_by]                VARCHAR (50)  NULL,
    [child_id]                         INT           NULL,
    [utilities]                        FLOAT (53)    NULL,
    [utilities_description]            VARCHAR (50)  NULL,
    [clothing]                         FLOAT (53)    NULL,
    [clothing_description]             VARCHAR (50)  NULL,
    [non_food]                         FLOAT (53)    NULL,
    [non_food_description]             VARCHAR (50)  NULL,
    [respite]                          FLOAT (53)    NULL,
    [respite_description]              VARCHAR (50)  NULL,
    [school]                           FLOAT (53)    NULL,
    [school_description]               VARCHAR (50)  NULL,
    [tenant_id]                        INT           NULL,
    CONSTRAINT [PK_respite_event_gap_fill] PRIMARY KEY CLUSTERED ([respite_event_gap_fill_id] ASC) WITH (FILLFACTOR = 90)
);

