CREATE TABLE [dbo].[STATE] (
    [STATE_ID]   INT           IDENTITY (1, 1) NOT NULL,
    [STATE]      NVARCHAR (50) NOT NULL,
    [STATE_NAME] NVARCHAR (50) NOT NULL,
    CONSTRAINT [PK__STATE__42ACE4D4] PRIMARY KEY NONCLUSTERED ([STATE_ID] ASC) WITH (FILLFACTOR = 90)
);

