CREATE TABLE [dbo].[titles] (
    [TITLE_ID]   SMALLINT     IDENTITY (1, 1) NOT NULL,
    [TITLE_TEXT] VARCHAR (50) NOT NULL,
    [tenant_id]  INT          NULL,
    CONSTRAINT [PK__TITLES__4589517F] PRIMARY KEY NONCLUSTERED ([TITLE_ID] ASC) WITH (FILLFACTOR = 90)
);

